name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    # - name: Audit
    #   run: cargo install cargo-audit && cargo audit
    - name: Check if version changed
      id: check-version
      run: |
        if git diff HEAD~1..HEAD -- Cargo.toml | grep -q "^+version = \"[0-9]\+\.[0-9]\+\.[0-9]\+\""
        then
          echo "changed=true" >> $GITHUB_ENV
        else
          echo "changed=false" >> $GITHUB_ENV
        fi
    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.changed == 'true'
